### ISSUE TITLE
Unexpected keys in dict when running evaluation

### ISSUE THREAD

**Issue by vadimkantorov** [dddzg/up-detr#2]
How can I evaluate the provided model? I'm trying to use the DETR's recipe and getting a checkpoint loading error.

Thank you!

```shell
DATASETROOT=$PWD/path/to/coco/

UPDETRCKPTURL='https://drive.google.com/file/d/1_YNtzKKaQbgFfd6m2ZUCO6LWpKqd7o7X'
UPDETRCKPT='up-detr-coco-fine-tuned-300ep.pt'

git clone https://github.com/dddzg/up-detr
cd up-detr

GOOGLE_DRIVE_FILE_ID=$(echo $UPDETRCKPTURL | rev | cut -d'/' -f1 | rev)
CONFIRM=$(wget --quiet --save-cookies googlecookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=$GOOGLE_DRIVE_FILE_ID" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
wget -O $UPDETRCKPT --load-cookies googlecookies.txt "https://docs.google.com/uc?export=download&confirm=$CONFIRM&id=$GOOGLE_DRIVE_FILE_ID"

python main_detr.py --batch_size 2 --no_aux_loss --eval --resume $UPDETRCKPT --coco_path $DATASETROOT
```

```
Not using distributed mode
git:
  sha: 00be9b996f52324335e0cc3fe7a59bfba9f43540, status: clean, branch: master

Namespace(aux_loss=False, backbone='resnet50', batch_size=2, bbox_loss_coef=5, clip_max_norm=0.1, coco_panoptic_path=None, coco_path='/specific/netapp5_2/gamir/lab/vadim/foo/../selfsupslots/data/common/coco/', dataset_file='coco', dec_layers=6, device='cuda', dice_loss_coef=1, dilation=False, dim_feedforward=2048, dist_url='env://', distributed=False, dropout=0.1, enc_layers=6, eos_coef=0.1, epochs=300, eval=True, frozen_weights=None, giou_loss_coef=2, hidden_dim=256, lr=0.0001, lr_backbone=1e-05, lr_drop=200, mask_loss_coef=1, masks=False, nheads=8, num_queries=100, num_workers=2, output_dir='', position_embedding='sine', pre_norm=False, pretrain='', remove_difficult=False, resume='up-detr-coco-fine-tuned-300ep.pt', seed=42, set_cost_bbox=5, set_cost_class=1, set_cost_giou=2, start_epoch=0, weight_decay=0.0001, world_size=1)
number of params: 41302368
loading annotations into memory...

Done (t=32.57s)
creating index...
index created!
loading annotations into memory...
Done (t=4.40s)
creating index...
index created!
Traceback (most recent call last):
  File "detr_main.py", line 267, in <module>
    main(args)
  File "detr_main.py", line 197, in main
    model_without_ddp.load_state_dict(checkpoint['model'])
  File ".../vadim/prefix/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DETR:
        Unexpected key(s) in state_dict: "transformer.encoder.norm.weight", "transformer.encoder.norm.bias".
```

**Comment by dddzg** [comment]
Thanks for your attention. you need to add `--pre_norm`.
In our experiments, we use  `--pre_norm` by default.
There are some papers (in NLP) noting that `--pre_norm` is a little better, so we use it in all of our experiments (including our reimplemented counterpart).
Feeling free to this setting, it does not affect too much performance of DETR.

**Comment by dddzg** [comment]
read more: https://github.com/facebookresearch/detr/issues/93
Because of the paper: https://arxiv.org/abs/2002.04745, so we adopt `--pre_norm` in our early experiments.

**Comment by vadimkantorov** [comment]
It works, thank you! Probably adding the full eval bash line to README would be a worthy thing.

**Comment by dddzg** [comment]
Thanks, we have updated the README!
